import type { Metadata } from 'next';
import '@/styles/globals.css';
import styles from './styles/Home.module.scss';

import RootContext from '@/context';
import MusicPlayer from '@/features/Player/Player';
import Navigation from '@/features/Navigation/Navigation';

export const metadata: Metadata = {
  title: 'Songfiy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootContext>
          <div className={styles.container}>
            <div className={styles.content}>
              <Navigation />
              <div className={styles.routes}>{children}</div>
            </div>
            <MusicPlayer />
          </div>
        </RootContext>
      </body>
    </html>
  );
}
