version: '3'
services:
  api:
    build: 
      context: .
      args:
        DB_HOST: ${DB_HOST}
    container_name: songfiy-api
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: unless-stopped
    command: npm run start:prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
