export const KEYWOARDS = {
  SONG_TITLE: [
    'music',
    'song',
    'vevo',
    'remix',
    'dubstep',
    'nightcore',
    'piano',
    'lyrics',
    'official video',
    'amv',
    'музыка',
    'ft.',
    'feat.',
    'explicit version',
    'audio',
    ' - ',
    ' — ',
    'tiktok mix',
    'cover',
    'opening',
    'full-version',
    'песни',
    'dubstep',
    'ncs',
    'литерал',
    'violin',
    'премьера клипа',
    'gingertail',
  ],
};
