import type { Metadata } from 'next';

import '@/styles/globals.css';
import RootContext from '@/context';
import { cookies } from 'next/headers';
import { Flip, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme')?.value || 'dark';

  return (
    <html lang="en" className={themeCookie}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <RootContext>
        <body>
          {children}
          <ToastContainer
            position="bottom-right"
            hideProgressBar
            newestOnTop
            theme={themeCookie}
            transition={Flip}
          />
        </body>
      </RootContext>
    </html>
  );
}
